[project]
name = "api-gateway"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.115.2",
    "httpx>=0.27.2",
    "uvicorn>=0.31.1",
]